.TH "ZTR" 1 "September 23 2021" "ztr 1.2.0" "User Commands"
.SH NAME
ztr \- zsh test runner

.SH SYNOPSIS

\fBztr clear\fR

\fBztr skip\fR [(\fI\-\-quiet | \-q\fR)] <\fIarg\fR> [\fI<name>\fR [\fI<notes>\fR]]\fR

\fBztr summary\fR

\fBztr test\fR [(\fI\-\-quiet | \-q\fR)] <\fIarg\fR> [\fI\-\-emulate <shell>\fR] [fI\-\-quiet\-emulate\fR] [\fI<name>\fR [\fI<notes>\fR]]\fR

\fBabbr\fR (\fBhelp | \-\-help\fR | \fB\-h\fR)

\fBabbr\fR (\fBversion | \-\-version\fR | \fB\-v\fR)

.SH DESCRIPTION

\fBztr\fR runs zsh tests, and logs individual and overall results in a human-readable format.

.SH Commands

.IP \(bu
\fBclear\fR

Clear results.

.IP \(bu
\fBskip \fI<arg>\fR [(\fI\-\-quiet | \-q\fR)] [\fI<name>\fR [\fI<notes>\fR]]\fR

Skip <arg>.

See \fBtest\fR for details about \fI\-\-quiet\fR, \fI<name>\fR, and \fI<notes>\fR.


.IP \(bu
\fBsummary\fR

Pretty-print summary of results.

.IP \(bu
\fBztr test\fR [(\fI\-\-quiet | \-q\fR)] <\fIarg\fR> [\fI\-\-emulate <shell>\fR] [fI\-\-quiet\-emulate\fR] [\fI<name>\fR [\fI<notes>\fR]]\fR

Test \fI<arg>\fR. Pretty-print result and notes unless "quiet".

If your arg will error when passed to `eval`, quote it. If your arg has spaces, quote it.

Optionally change zsh's emulation mode.

Optionally do not warn when a non-zsh shell is emulated.

Optionally pass a name as a second parameter.

Optionally pass notes as a third parameter. For example, noting dependencies can help with troubleshooting. In the output notes are indented.

.IP \(bu
\fBhelp\fR or \fB\-\-help\fR or \fB\-h\fR

Show the manpage.

.IP \(bu
\fBversion\fR or \fB\-\-version\fR or \fB\-v\fR

Print the command name and current version.

.\" .SH EXAMPLES

.SH LICENSE

zsh-test-runner by Henry Bley-Vroman is licensed under a license which is the unmodified text of CC BY-NC-SA 4.0 and the unmodified text of a Hippocratic License 3. It is not affiliated with Creative Commons or the Organization for Ethical Source. See the LICENSE file for details. Persons interested in using or
adapting this work for commercial purposes should contact the author.

.SH HOMEPAGE

Explanations and examples can be found at https://github.com/olets/zsh-test-runner

.SH AUTHORS

Henry Bley\-Vroman <olets@olets.dev>
