.TH "ZTR" 1 "March 28 2021" "ztr 1.1.1" "User Commands"
.SH NAME
ztr \- zsh test runner

.SH SYNOPSIS

\fBztr clear\fR

\fBztr skip\fR [(\fI\-\-quiet | \-q\fR)] <\fIarg\fR> [\fI<name>\fR [\fI<notes>\fR]]\fR

\fBztr summary\fR

\fBztr test\fR [(\fI\-\-quiet | \-q\fR)] <\fIarg\fR> [\fI<name>\fR [\fI<notes>\fR]]\fR

\fBabbr\fR (\fBhelp | \-\-help\fR | \fB\-h\fR)

\fBabbr\fR (\fBversion | \-\-version\fR | \fB\-v\fR)

.SH DESCRIPTION

\fBztr\fR runs zsh tests, and logs individual and overall results in a human-readable format.

.SH Commands

.IP \(bu
\fBclear\fR

Clear results.

.IP \(bu
\fBskip \fI<arg>\fR [(\fI\-\-quiet | \-q\fR)] [\fI<name>\fR [\fI<notes>\fR]]\fR

Skip <arg>.

See \fBtest\fR for details about \fI\-\-quiet\fR, \fI<name>\fR, and \fI<notes>\fR.


.IP \(bu
\fBsummary\fR

Pretty-print summary of results.

.IP \(bu
\fBtest \fI<arg>\fR [(\fI\-\-quiet | \-q\fR)] [\fI<name>\fR [\fI<notes>\fR]]\fR

Test \fI<arg>\fR. Pretty-print result and notes unless "quiet".

If your arg will error when passed to `eval`, quote it. If your arg has spaces, quote it.

Optionally pass a name as a second parameter.

Optionally pass notes as a third parameter. For example, noting dependencies can help with troubleshooting. In the output notes are indented.

.IP \(bu
\fBhelp\fR or \fB\-\-help\fR or \fB\-h\fR

Show the manpage.

.IP \(bu
\fBversion\fR or \fB\-\-version\fR or \fB\-v\fR

Print the command name and current version.

.\" .SH EXAMPLES

.SH LICENSE

Licensed under CC BY-NC-SA 4.0 with a human rights condition from Hippocratic
License 2.1. See the LICENSE file for details. Persons interested in using or
adapting this work for commercial purposes should contact the author.

.SH HOMEPAGE

Explanations and examples can be found at https://github.com/olets/zsh-test-runner

.SH AUTHORS

Henry Bley\-Vroman <olets@olets.dev>
